name: Check Cesium Updates

# Add permissions configuration
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check for Cesium updates
        id: check-version
        run: |
          # Get latest Cesium version from npm
          LATEST_VERSION=$(deno eval "
            const response = await fetch('https://registry.npmjs.org/cesium/latest');
            const data = await response.json();
            console.log(data.version);
          ")
          
          # Get current version from index.html
          CURRENT_VERSION=$(grep -oP 'releases/\K[0-9.]+(?=/Build/Cesium)' index.html | head -1)
          
          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"
          
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "new_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "update_needed=true" >> $GITHUB_OUTPUT
            
            # Update the version in index.html
            sed -i "s|releases/$CURRENT_VERSION/Build|releases/$LATEST_VERSION/Build|g" index.html
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-version.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Cesium to version ${{ steps.check-version.outputs.new_version }}"
          body: |
            This PR updates Cesium from version ${{ steps.check-version.outputs.current_version }} to ${{ steps.check-version.outputs.new_version }}.
            
            Changes made:
            - Updated Cesium.js script source
            - Updated widgets.css stylesheet source
          branch: update-cesium-version
          base: main
          delete-branch: true
          commit-message: |
            Update Cesium to version ${{ steps.check-version.outputs.new_version }}
            
            - Updated Cesium.js script source
            - Updated widgets.css stylesheet source
          committer: GitHub Actions <github-actions@github.com>
          author: GitHub Actions <github-actions@github.com>
          signoff: true 